#!/usr/bin/env python3
"""Generate doc/i18n/pms-modules-keys.json for all 21 app locales."""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "doc" / "i18n" / "pms-modules-keys.json"
LOCALES_DIR = ROOT / "public" / "assets" / "locales"

APP_LOCALES = [
    "ar", "de", "en", "es", "fr", "he", "hi", "id", "it", "ja", "ko", "lo",
    "nl", "pl", "pt-BR", "ru", "th", "tr", "vi", "zh-Hans", "zh-Hant",
]

EMBEDDED_LOCALES = [
    "he", "th", "es", "fr", "de", "it", "ar", "hi", "vi", "id", "tr", "ja",
    "ko", "ru", "pt-BR", "zh-Hans", "nl",
]

TRANSLATE_TARGETS = {
    "pl": "pl",
    "lo": "lo",
    "zh-Hant": "zh-TW",
}

EN: dict[str, str] = {
    "sysTitle": "Hotel Restaurant Mini-Mart Management",
    "btnAddRoom": "Add Room",
    "btnAddBk": "Add Booking",
    "btnAddGst": "Add Guest",
    "btnAddCln": "Add Cleaning",
    "btnAddTask": "Add Task",
    "btnAddSvc": "Add Service",
    "btnAddInv": "Add Invoice",
    "btnAddStk": "Add Stock",
    "btnAddMenu": "Add Menu",
    "btnAddShop": "Add Shop Item",
    "btnAddTx": "Add Transaction",
    "btnAddUsr": "Add User",
    "rTitle": "Room",
    "rNum": "Room No.",
    "rType": "Type",
    "rSgl": "Single",
    "rDbl": "Double",
    "rSte": "Suite",
    "rBtn": "Add Room",
    "bTitle": "Booking",
    "bGst": "Guest",
    "bRm": "Room",
    "bDate": "Date",
    "bBtn": "Add Booking",
    "gTitle": "Guest",
    "gName": "Name",
    "gPhone": "Phone",
    "gId": "ID",
    "gBtn": "Add Guest",
    "cTitle": "Cleaning",
    "cRm": "Room",
    "cStat": "Status",
    "cCln": "Clean",
    "cDrt": "Dirty",
    "cPrg": "In Progress",
    "cBtn": "Save",
    "tTitle": "Task",
    "tIssue": "Issue",
    "tLoc": "Location",
    "tBtn": "Save",
    "sTitle": "Service",
    "sRm": "Room",
    "sDesc": "Description",
    "sBtn": "Save",
    "iTitle": "Invoice",
    "iRef": "Reference",
    "iAmt": "Amount",
    "iBtn": "Save",
    "stTitle": "Stock",
    "stItem": "Item",
    "stQty": "Qty",
    "stBtn": "Save",
    "mTitle": "Menu",
    "mDish": "Dish",
    "mPrc": "Price",
    "mBtn": "Save",
    "shTitle": "Shop",
    "shProd": "Product",
    "shPrc": "Price",
    "shBtn": "Save",
    "xTitle": "Transaction",
    "xDesc": "Description",
    "xAmt": "Amount",
    "xBtn": "Save",
    "uTitle": "User",
    "uUser": "Username",
    "uRole": "Role",
    "uAdm": "Admin",
    "uRec": "Reception",
    "uStf": "Staff",
    "uBtn": "Save",
}

# Maps pms key -> (locale section, locale key) for embedded locales from app locale files.
SOURCE_MAP: dict[str, tuple[str, str]] = {
    "sysTitle": ("setup", "sysHeaderTitle"),
    "btnAddRoom": ("rooms", "addRoom"),
    "btnAddBk": ("book", "addNew"),
    "btnAddGst": ("guest", "btnAdd"),
    "btnAddCln": ("nav", "housekeeping"),
    "btnAddTask": ("nav", "maintenance"),
    "btnAddSvc": ("msg", "addService"),
    "btnAddInv": ("nav", "invoices"),
    "btnAddStk": ("inventory", "addItemBtn"),
    "btnAddMenu": ("common", "addMenuItem"),
    "btnAddShop": ("common", "addStoreItem"),
    "btnAddTx": ("nav", "transactions"),
    "btnAddUsr": ("pageTitle", "accounts"),
    "rTitle": ("pageTitle", "rooms"),
    "rNum": ("rooms", "fieldRoomNumber"),
    "rType": ("rooms", "fieldRoomType"),
    "rSgl": ("housekeeping", "typeSingle"),
    "rDbl": ("housekeeping", "typeDouble"),
    "rSte": ("housekeeping", "typeSuite"),
    "rBtn": ("rooms", "addRoom"),
    "bTitle": ("pageTitle", "bookings"),
    "bGst": ("g", "guest"),
    "bRm": ("g", "room"),
    "bDate": ("g", "date"),
    "bBtn": ("book", "btnCreateBooking"),
    "gTitle": ("guest", "addTitle"),
    "gName": ("g", "name"),
    "gPhone": ("g", "phone"),
    "gId": ("book", "labelGuestId"),
    "gBtn": ("guest", "btnAdd"),
    "cTitle": ("pageTitle", "housekeeping"),
    "cRm": ("housekeeping", "fieldRoom"),
    "cStat": ("g", "status"),
    "cCln": ("housekeeping", "statusClean"),
    "cDrt": ("housekeeping", "statusDirty"),
    "cPrg": ("housekeeping", "statusInProgress"),
    "cBtn": ("common", "save"),
    "tTitle": ("pageTitle", "maintenance"),
    "tIssue": ("g", "issue"),
    "tLoc": ("g", "module"),
    "tBtn": ("common", "save"),
    "sTitle": ("pageTitle", "services"),
    "sRm": ("g", "room"),
    "sDesc": ("g", "description"),
    "sBtn": ("common", "save"),
    "iTitle": ("pageTitle", "invoices"),
    "iRef": ("g", "bookingId"),
    "iAmt": ("g", "total"),
    "iBtn": ("common", "save"),
    "stTitle": ("pageTitle", "inventory"),
    "stItem": ("g", "itemName"),
    "stQty": ("g", "quantity"),
    "stBtn": ("common", "save"),
    "mTitle": ("pageTitle", "menuitems"),
    "mDish": ("restaurant", "addProduct"),
    "mPrc": ("g", "price"),
    "mBtn": ("common", "save"),
    "shTitle": ("pageTitle", "storeitems"),
    "shProd": ("minimart", "addStoreItemBtn"),
    "shPrc": ("g", "price"),
    "shBtn": ("common", "save"),
    "xTitle": ("pageTitle", "alltransactions"),
    "xDesc": ("g", "description"),
    "xAmt": ("g", "total"),
    "xBtn": ("common", "save"),
    "uTitle": ("pageTitle", "accounts"),
    "uUser": ("login", "username"),
    "uRole": ("login", "role"),
    "uAdm": ("login", "roleAdmin"),
    "uRec": ("login", "roleReception"),
    "uStf": ("g", "staff"),
    "uBtn": ("common", "save"),
}

# Complete Dutch (mockup was cut off at rBtn: "Kamer").
EMBEDDED_NL: dict[str, str] = {
    "sysTitle": "Beheer van hotel, restaurant en minimarkt",
    "btnAddRoom": "Kamer toevoegen",
    "btnAddBk": "Nieuwe boeking toevoegen",
    "btnAddGst": "Gast toevoegen",
    "btnAddCln": "Schoonmaak toevoegen",
    "btnAddTask": "Taak toevoegen",
    "btnAddSvc": "Service toevoegen",
    "btnAddInv": "Factuur toevoegen",
    "btnAddStk": "Voorraad toevoegen",
    "btnAddMenu": "Menu toevoegen",
    "btnAddShop": "Winkelartikel toevoegen",
    "btnAddTx": "Transactie toevoegen",
    "btnAddUsr": "Gebruiker toevoegen",
    "rTitle": "Kamer",
    "rNum": "Kamernummer",
    "rType": "Kamertype",
    "rSgl": "Eenpersoons",
    "rDbl": "Tweepersoons",
    "rSte": "Suite",
    "rBtn": "Kamer toevoegen",
    "bTitle": "Boeking",
    "bGst": "Gast",
    "bRm": "Kamer",
    "bDate": "Datum",
    "bBtn": "Boeking toevoegen",
    "gTitle": "Gast",
    "gName": "Naam",
    "gPhone": "Telefoon",
    "gId": "ID",
    "gBtn": "Gast toevoegen",
    "cTitle": "Schoonmaak",
    "cRm": "Kamer",
    "cStat": "Status",
    "cCln": "Schoon",
    "cDrt": "Vies",
    "cPrg": "Bezig",
    "cBtn": "Opslaan",
    "tTitle": "Taak",
    "tIssue": "Probleem",
    "tLoc": "Locatie",
    "tBtn": "Opslaan",
    "sTitle": "Service",
    "sRm": "Kamer",
    "sDesc": "Beschrijving",
    "sBtn": "Opslaan",
    "iTitle": "Factuur",
    "iRef": "Referentie",
    "iAmt": "Bedrag",
    "iBtn": "Opslaan",
    "stTitle": "Voorraad",
    "stItem": "Artikel",
    "stQty": "Aantal",
    "stBtn": "Opslaan",
    "mTitle": "Menu",
    "mDish": "Gerecht",
    "mPrc": "Prijs",
    "mBtn": "Opslaan",
    "shTitle": "Winkel",
    "shProd": "Product",
    "shPrc": "Prijs",
    "shBtn": "Opslaan",
    "xTitle": "Transactie",
    "xDesc": "Beschrijving",
    "xAmt": "Bedrag",
    "xBtn": "Opslaan",
    "uTitle": "Gebruiker",
    "uUser": "Gebruikersnaam",
    "uRole": "Rol",
    "uAdm": "Beheerder",
    "uRec": "Receptie",
    "uStf": "Personeel",
    "uBtn": "Opslaan",
}

# Full embedded translations from user HTML mockup / app locale dictionary.
EMBEDDED: dict[str, dict[str, str]] = {
    "he": {
        "sysTitle": "ניהול מלון, מסעדה ומינימרקט",
        "btnAddRoom": "הוסף חדר",
        "btnAddBk": "הוסף הזמנה חדשה",
        "btnAddGst": "הוסף אורח",
        "btnAddCln": "הוסף ניקיון",
        "btnAddTask": "הוסף משימה",
        "btnAddSvc": "הוסף שירות",
        "btnAddInv": "הוסף חשבונית",
        "btnAddStk": "הוסף מלאי",
        "btnAddMenu": "הוסף תפריט",
        "btnAddShop": "הוסף פריט חנות",
        "btnAddTx": "הוסף עסקה",
        "btnAddUsr": "הוסף משתמש",
        "rTitle": "חדר",
        "rNum": "מספר חדר",
        "rType": "סוג חדר",
        "rSgl": "יחיד",
        "rDbl": "זוגי",
        "rSte": "סוויטה",
        "rBtn": "הוסף חדר",
        "bTitle": "הזמנה",
        "bGst": "אורח",
        "bRm": "חדר",
        "bDate": "תאריך",
        "bBtn": "הוסף הזמנה",
        "gTitle": "אורח",
        "gName": "שם",
        "gPhone": "טלפון",
        "gId": "מזהה",
        "gBtn": "הוסף אורח",
        "cTitle": "ניקיון",
        "cRm": "חדר",
        "cStat": "סטטוס",
        "cCln": "נקי",
        "cDrt": "מלוכלך",
        "cPrg": "בתהליך",
        "cBtn": "שמור",
        "tTitle": "משימה",
        "tIssue": "בעיה",
        "tLoc": "מיקום",
        "tBtn": "שמור",
        "sTitle": "שירות",
        "sRm": "חדר",
        "sDesc": "תיאור",
        "sBtn": "שמור",
        "iTitle": "חשבונית",
        "iRef": "אסמכתא",
        "iAmt": "סכום",
        "iBtn": "שמור",
        "stTitle": "מלאי",
        "stItem": "פריט",
        "stQty": "כמות",
        "stBtn": "שמור",
        "mTitle": "תפריט",
        "mDish": "מנה",
        "mPrc": "מחיר",
        "mBtn": "שמור",
        "shTitle": "חנות",
        "shProd": "מוצר",
        "shPrc": "מחיר",
        "shBtn": "שמור",
        "xTitle": "עסקה",
        "xDesc": "תיאור",
        "xAmt": "סכום",
        "xBtn": "שמור",
        "uTitle": "משתמש",
        "uUser": "שם משתמש",
        "uRole": "תפקיד",
        "uAdm": "מנהל",
        "uRec": "קבלה",
        "uStf": "צוות",
        "uBtn": "שמור",
    },
    "th": {
        "sysTitle": "การจัดการโรงแรม ร้านอาหาร และมินิมาร์ท",
        "btnAddRoom": "เพิ่มห้อง",
        "btnAddBk": "เพิ่มการจองใหม่",
        "btnAddGst": "เพิ่มแขก",
        "btnAddCln": "เพิ่มการทำความสะอาด",
        "btnAddTask": "เพิ่มงาน",
        "btnAddSvc": "เพิ่มบริการ",
        "btnAddInv": "เพิ่มใบแจ้งหนี้",
        "btnAddStk": "เพิ่มสต็อก",
        "btnAddMenu": "เพิ่มเมนู",
        "btnAddShop": "เพิ่มสินค้าร้าน",
        "btnAddTx": "เพิ่มธุรกรรม",
        "btnAddUsr": "เพิ่มผู้ใช้",
        "rTitle": "ห้อง",
        "rNum": "เลขห้อง",
        "rType": "ประเภทห้อง",
        "rSgl": "เดี่ยว",
        "rDbl": "คู่",
        "rSte": "ห้องสวีท",
        "rBtn": "เพิ่มห้อง",
        "bTitle": "การจอง",
        "bGst": "แขก",
        "bRm": "ห้อง",
        "bDate": "วันที่",
        "bBtn": "เพิ่มการจอง",
        "gTitle": "แขก",
        "gName": "ชื่อ",
        "gPhone": "โทรศัพท์",
        "gId": "รหัส",
        "gBtn": "เพิ่มแขก",
        "cTitle": "ทำความสะอาด",
        "cRm": "ห้อง",
        "cStat": "สถานะ",
        "cCln": "สะอาด",
        "cDrt": "สกปรก",
        "cPrg": "กำลังดำเนินการ",
        "cBtn": "บันทึก",
        "tTitle": "งาน",
        "tIssue": "ปัญหา",
        "tLoc": "ตำแหน่ง",
        "tBtn": "บันทึก",
        "sTitle": "บริการ",
        "sRm": "ห้อง",
        "sDesc": "คำอธิบาย",
        "sBtn": "บันทึก",
        "iTitle": "ใบแจ้งหนี้",
        "iRef": "อ้างอิง",
        "iAmt": "จำนวนเงิน",
        "iBtn": "บันทึก",
        "stTitle": "สต็อก",
        "stItem": "รายการ",
        "stQty": "จำนวน",
        "stBtn": "บันทึก",
        "mTitle": "เมนู",
        "mDish": "อาหาร",
        "mPrc": "ราคา",
        "mBtn": "บันทึก",
        "shTitle": "ร้านค้า",
        "shProd": "สินค้า",
        "shPrc": "ราคา",
        "shBtn": "บันทึก",
        "xTitle": "ธุรกรรม",
        "xDesc": "คำอธิบาย",
        "xAmt": "จำนวนเงิน",
        "xBtn": "บันทึก",
        "uTitle": "ผู้ใช้",
        "uUser": "ชื่อผู้ใช้",
        "uRole": "บทบาท",
        "uAdm": "ผู้ดูแล",
        "uRec": "แผนกต้อนรับ",
        "uStf": "พนักงาน",
        "uBtn": "บันทึก",
    },
    "es": {
        "sysTitle": "Gestión de hotel, restaurante y minimarket",
        "btnAddRoom": "Agregar habitación",
        "btnAddBk": "Agregar nueva reserva",
        "btnAddGst": "Agregar huésped",
        "btnAddCln": "Agregar limpieza",
        "btnAddTask": "Agregar tarea",
        "btnAddSvc": "Agregar servicio",
        "btnAddInv": "Agregar factura",
        "btnAddStk": "Agregar stock",
        "btnAddMenu": "Agregar menú",
        "btnAddShop": "Agregar artículo de tienda",
        "btnAddTx": "Agregar transacción",
        "btnAddUsr": "Agregar usuario",
        "rTitle": "Habitación",
        "rNum": "Número de habitación",
        "rType": "Tipo de habitación",
        "rSgl": "Individual",
        "rDbl": "Doble",
        "rSte": "Suite",
        "rBtn": "Agregar habitación",
        "bTitle": "Reserva",
        "bGst": "Huésped",
        "bRm": "Habitación",
        "bDate": "Fecha",
        "bBtn": "Agregar reserva",
        "gTitle": "Huésped",
        "gName": "Nombre",
        "gPhone": "Teléfono",
        "gId": "ID",
        "gBtn": "Agregar huésped",
        "cTitle": "Limpieza",
        "cRm": "Habitación",
        "cStat": "Estado",
        "cCln": "Limpio",
        "cDrt": "Sucio",
        "cPrg": "En progreso",
        "cBtn": "Guardar",
        "tTitle": "Tarea",
        "tIssue": "Problema",
        "tLoc": "Ubicación",
        "tBtn": "Guardar",
        "sTitle": "Servicio",
        "sRm": "Habitación",
        "sDesc": "Descripción",
        "sBtn": "Guardar",
        "iTitle": "Factura",
        "iRef": "Referencia",
        "iAmt": "Importe",
        "iBtn": "Guardar",
        "stTitle": "Stock",
        "stItem": "Artículo",
        "stQty": "Cantidad",
        "stBtn": "Guardar",
        "mTitle": "Menú",
        "mDish": "Plato",
        "mPrc": "Precio",
        "mBtn": "Guardar",
        "shTitle": "Tienda",
        "shProd": "Producto",
        "shPrc": "Precio",
        "shBtn": "Guardar",
        "xTitle": "Transacción",
        "xDesc": "Descripción",
        "xAmt": "Importe",
        "xBtn": "Guardar",
        "uTitle": "Usuario",
        "uUser": "Nombre de usuario",
        "uRole": "Rol",
        "uAdm": "Administrador",
        "uRec": "Recepción",
        "uStf": "Personal",
        "uBtn": "Guardar",
    },
    "fr": {
        "sysTitle": "Gestion d'hôtel, de restaurant et de supérette",
        "btnAddRoom": "Ajouter une chambre",
        "btnAddBk": "Ajouter une réservation",
        "btnAddGst": "Ajouter un invité",
        "btnAddCln": "Ajouter un nettoyage",
        "btnAddTask": "Ajouter une tâche",
        "btnAddSvc": "Ajouter un service",
        "btnAddInv": "Ajouter une facture",
        "btnAddStk": "Ajouter du stock",
        "btnAddMenu": "Ajouter un menu",
        "btnAddShop": "Ajouter un article boutique",
        "btnAddTx": "Ajouter une transaction",
        "btnAddUsr": "Ajouter un utilisateur",
        "rTitle": "Chambre",
        "rNum": "Numéro de chambre",
        "rType": "Type de chambre",
        "rSgl": "Simple",
        "rDbl": "Double",
        "rSte": "Suite",
        "rBtn": "Ajouter une chambre",
        "bTitle": "Réservation",
        "bGst": "Invité",
        "bRm": "Chambre",
        "bDate": "Date",
        "bBtn": "Ajouter une réservation",
        "gTitle": "Invité",
        "gName": "Nom",
        "gPhone": "Téléphone",
        "gId": "ID",
        "gBtn": "Ajouter un invité",
        "cTitle": "Nettoyage",
        "cRm": "Chambre",
        "cStat": "Statut",
        "cCln": "Propre",
        "cDrt": "Sale",
        "cPrg": "En cours",
        "cBtn": "Enregistrer",
        "tTitle": "Tâche",
        "tIssue": "Problème",
        "tLoc": "Emplacement",
        "tBtn": "Enregistrer",
        "sTitle": "Service",
        "sRm": "Chambre",
        "sDesc": "Description",
        "sBtn": "Enregistrer",
        "iTitle": "Facture",
        "iRef": "Référence",
        "iAmt": "Montant",
        "iBtn": "Enregistrer",
        "stTitle": "Stock",
        "stItem": "Article",
        "stQty": "Quantité",
        "stBtn": "Enregistrer",
        "mTitle": "Menu",
        "mDish": "Plat",
        "mPrc": "Prix",
        "mBtn": "Enregistrer",
        "shTitle": "Boutique",
        "shProd": "Produit",
        "shPrc": "Prix",
        "shBtn": "Enregistrer",
        "xTitle": "Transaction",
        "xDesc": "Description",
        "xAmt": "Montant",
        "xBtn": "Enregistrer",
        "uTitle": "Utilisateur",
        "uUser": "Nom d'utilisateur",
        "uRole": "Rôle",
        "uAdm": "Admin",
        "uRec": "Réception",
        "uStf": "Personnel",
        "uBtn": "Enregistrer",
    },
    "de": {
        "sysTitle": "Hotel-, Restaurant- und Minimarkt-Management",
        "btnAddRoom": "Zimmer hinzufügen",
        "btnAddBk": "Neue Buchung hinzufügen",
        "btnAddGst": "Gast hinzufügen",
        "btnAddCln": "Reinigung hinzufügen",
        "btnAddTask": "Aufgabe hinzufügen",
        "btnAddSvc": "Service hinzufügen",
        "btnAddInv": "Rechnung hinzufügen",
        "btnAddStk": "Bestand hinzufügen",
        "btnAddMenu": "Menü hinzufügen",
        "btnAddShop": "Shop-Artikel hinzufügen",
        "btnAddTx": "Transaktion hinzufügen",
        "btnAddUsr": "Benutzer hinzufügen",
        "rTitle": "Zimmer",
        "rNum": "Zimmernummer",
        "rType": "Zimmertyp",
        "rSgl": "Einzel",
        "rDbl": "Doppel",
        "rSte": "Suite",
        "rBtn": "Zimmer hinzufügen",
        "bTitle": "Buchung",
        "bGst": "Gast",
        "bRm": "Zimmer",
        "bDate": "Datum",
        "bBtn": "Buchung hinzufügen",
        "gTitle": "Gast",
        "gName": "Name",
        "gPhone": "Telefon",
        "gId": "ID",
        "gBtn": "Gast hinzufügen",
        "cTitle": "Reinigung",
        "cRm": "Zimmer",
        "cStat": "Status",
        "cCln": "Sauber",
        "cDrt": "Schmutzig",
        "cPrg": "In Bearbeitung",
        "cBtn": "Speichern",
        "tTitle": "Aufgabe",
        "tIssue": "Problem",
        "tLoc": "Standort",
        "tBtn": "Speichern",
        "sTitle": "Service",
        "sRm": "Zimmer",
        "sDesc": "Beschreibung",
        "sBtn": "Speichern",
        "iTitle": "Rechnung",
        "iRef": "Referenz",
        "iAmt": "Betrag",
        "iBtn": "Speichern",
        "stTitle": "Bestand",
        "stItem": "Artikel",
        "stQty": "Menge",
        "stBtn": "Speichern",
        "mTitle": "Menü",
        "mDish": "Gericht",
        "mPrc": "Preis",
        "mBtn": "Speichern",
        "shTitle": "Shop",
        "shProd": "Produkt",
        "shPrc": "Preis",
        "shBtn": "Speichern",
        "xTitle": "Transaktion",
        "xDesc": "Beschreibung",
        "xAmt": "Betrag",
        "xBtn": "Speichern",
        "uTitle": "Benutzer",
        "uUser": "Benutzername",
        "uRole": "Rolle",
        "uAdm": "Admin",
        "uRec": "Rezeption",
        "uStf": "Personal",
        "uBtn": "Speichern",
    },
    "it": {
        "sysTitle": "Gestione di hotel, ristorante e minimarket",
        "btnAddRoom": "Aggiungi camera",
        "btnAddBk": "Aggiungi nuova prenotazione",
        "btnAddGst": "Aggiungi ospite",
        "btnAddCln": "Aggiungi pulizia",
        "btnAddTask": "Aggiungi attività",
        "btnAddSvc": "Aggiungi servizio",
        "btnAddInv": "Aggiungi fattura",
        "btnAddStk": "Aggiungi scorte",
        "btnAddMenu": "Aggiungi menu",
        "btnAddShop": "Aggiungi articolo negozio",
        "btnAddTx": "Aggiungi transazione",
        "btnAddUsr": "Aggiungi utente",
        "rTitle": "Camera",
        "rNum": "Numero camera",
        "rType": "Tipo camera",
        "rSgl": "Singola",
        "rDbl": "Doppia",
        "rSte": "Suite",
        "rBtn": "Aggiungi camera",
        "bTitle": "Prenotazione",
        "bGst": "Ospite",
        "bRm": "Camera",
        "bDate": "Data",
        "bBtn": "Aggiungi prenotazione",
        "gTitle": "Ospite",
        "gName": "Nome",
        "gPhone": "Telefono",
        "gId": "ID",
        "gBtn": "Aggiungi ospite",
        "cTitle": "Pulizia",
        "cRm": "Camera",
        "cStat": "Stato",
        "cCln": "Pulito",
        "cDrt": "Sporco",
        "cPrg": "In corso",
        "cBtn": "Salva",
        "tTitle": "Attività",
        "tIssue": "Problema",
        "tLoc": "Posizione",
        "tBtn": "Salva",
        "sTitle": "Servizio",
        "sRm": "Camera",
        "sDesc": "Descrizione",
        "sBtn": "Salva",
        "iTitle": "Fattura",
        "iRef": "Riferimento",
        "iAmt": "Importo",
        "iBtn": "Salva",
        "stTitle": "Scorte",
        "stItem": "Articolo",
        "stQty": "Quantità",
        "stBtn": "Salva",
        "mTitle": "Menu",
        "mDish": "Piatto",
        "mPrc": "Prezzo",
        "mBtn": "Salva",
        "shTitle": "Negozio",
        "shProd": "Prodotto",
        "shPrc": "Prezzo",
        "shBtn": "Salva",
        "xTitle": "Transazione",
        "xDesc": "Descrizione",
        "xAmt": "Importo",
        "xBtn": "Salva",
        "uTitle": "Utente",
        "uUser": "Nome utente",
        "uRole": "Ruolo",
        "uAdm": "Admin",
        "uRec": "Reception",
        "uStf": "Personale",
        "uBtn": "Salva",
    },
    "ar": {
        "sysTitle": "إدارة الفنادق والمطاعم والمحلات التجارية الصغيرة",
        "btnAddRoom": "إضافة غرفة",
        "btnAddBk": "إضافة حجز جديد",
        "btnAddGst": "إضافة ضيف",
        "btnAddCln": "إضافة تنظيف",
        "btnAddTask": "إضافة مهمة",
        "btnAddSvc": "إضافة خدمة",
        "btnAddInv": "إضافة فاتورة",
        "btnAddStk": "إضافة مخزون",
        "btnAddMenu": "إضافة قائمة",
        "btnAddShop": "إضافة منتج متجر",
        "btnAddTx": "إضافة معاملة",
        "btnAddUsr": "إضافة مستخدم",
        "rTitle": "غرفة",
        "rNum": "رقم الغرفة",
        "rType": "نوع الغرفة",
        "rSgl": "فردي",
        "rDbl": "مزدوج",
        "rSte": "جناح",
        "rBtn": "إضافة غرفة",
        "bTitle": "حجز",
        "bGst": "ضيف",
        "bRm": "غرفة",
        "bDate": "تاريخ",
        "bBtn": "إضافة حجز",
        "gTitle": "ضيف",
        "gName": "الاسم",
        "gPhone": "الهاتف",
        "gId": "المعرف",
        "gBtn": "إضافة ضيف",
        "cTitle": "تنظيف",
        "cRm": "غرفة",
        "cStat": "الحالة",
        "cCln": "نظيف",
        "cDrt": "متسخ",
        "cPrg": "قيد التنفيذ",
        "cBtn": "حفظ",
        "tTitle": "مهمة",
        "tIssue": "مشكلة",
        "tLoc": "الموقع",
        "tBtn": "حفظ",
        "sTitle": "خدمة",
        "sRm": "غرفة",
        "sDesc": "الوصف",
        "sBtn": "حفظ",
        "iTitle": "فاتورة",
        "iRef": "مرجع",
        "iAmt": "المبلغ",
        "iBtn": "حفظ",
        "stTitle": "مخزون",
        "stItem": "عنصر",
        "stQty": "الكمية",
        "stBtn": "حفظ",
        "mTitle": "قائمة",
        "mDish": "طبق",
        "mPrc": "السعر",
        "mBtn": "حفظ",
        "shTitle": "متجر",
        "shProd": "منتج",
        "shPrc": "السعر",
        "shBtn": "حفظ",
        "xTitle": "معاملة",
        "xDesc": "الوصف",
        "xAmt": "المبلغ",
        "xBtn": "حفظ",
        "uTitle": "مستخدم",
        "uUser": "اسم المستخدم",
        "uRole": "الدور",
        "uAdm": "مسؤول",
        "uRec": "الاستقبال",
        "uStf": "الموظفون",
        "uBtn": "حفظ",
    },
    "hi": {
        "sysTitle": "होटल, रेस्तरां और मिनीमार्ट प्रबंधन",
        "btnAddRoom": "कमरा जोड़ें",
        "btnAddBk": "नई बुकिंग जोड़ें",
        "btnAddGst": "अतिथि जोड़ें",
        "btnAddCln": "सफाई जोड़ें",
        "btnAddTask": "कार्य जोड़ें",
        "btnAddSvc": "सेवा जोड़ें",
        "btnAddInv": "चालान जोड़ें",
        "btnAddStk": "स्टॉक जोड़ें",
        "btnAddMenu": "मेनू जोड़ें",
        "btnAddShop": "दुकान आइटम जोड़ें",
        "btnAddTx": "लेनदेन जोड़ें",
        "btnAddUsr": "उपयोगकर्ता जोड़ें",
        "rTitle": "कमरा",
        "rNum": "कमरा नंबर",
        "rType": "कमरे का प्रकार",
        "rSgl": "सिंगल",
        "rDbl": "डबल",
        "rSte": "सुइट",
        "rBtn": "कमरा जोड़ें",
        "bTitle": "बुकिंग",
        "bGst": "अतिथि",
        "bRm": "कमरा",
        "bDate": "तारीख",
        "bBtn": "बुकिंग जोड़ें",
        "gTitle": "अतिथि",
        "gName": "नाम",
        "gPhone": "फ़ोन",
        "gId": "आईडी",
        "gBtn": "अतिथि जोड़ें",
        "cTitle": "सफाई",
        "cRm": "कमरा",
        "cStat": "स्थिति",
        "cCln": "साफ़",
        "cDrt": "गंदा",
        "cPrg": "प्रगति में",
        "cBtn": "सहेजें",
        "tTitle": "कार्य",
        "tIssue": "समस्या",
        "tLoc": "स्थान",
        "tBtn": "सहेजें",
        "sTitle": "सेवा",
        "sRm": "कमरा",
        "sDesc": "विवरण",
        "sBtn": "सहेजें",
        "iTitle": "चालान",
        "iRef": "संदर्भ",
        "iAmt": "राशि",
        "iBtn": "सहेजें",
        "stTitle": "स्टॉक",
        "stItem": "आइटम",
        "stQty": "मात्रा",
        "stBtn": "सहेजें",
        "mTitle": "मेनू",
        "mDish": "व्यंजन",
        "mPrc": "कीमत",
        "mBtn": "सहेजें",
        "shTitle": "दुकान",
        "shProd": "उत्पाद",
        "shPrc": "कीमत",
        "shBtn": "सहेजें",
        "xTitle": "लेनदेन",
        "xDesc": "विवरण",
        "xAmt": "राशि",
        "xBtn": "सहेजें",
        "uTitle": "उपयोगकर्ता",
        "uUser": "उपयोगकर्ता नाम",
        "uRole": "भूमिका",
        "uAdm": "व्यवस्थापक",
        "uRec": "रिसेप्शन",
        "uStf": "कर्मचारी",
        "uBtn": "सहेजें",
    },
    "vi": {
        "sysTitle": "Quản lý khách sạn, nhà hàng và siêu thị mini",
        "btnAddRoom": "Thêm phòng",
        "btnAddBk": "Thêm đặt phòng mới",
        "btnAddGst": "Thêm khách",
        "btnAddCln": "Thêm dọn phòng",
        "btnAddTask": "Thêm công việc",
        "btnAddSvc": "Thêm dịch vụ",
        "btnAddInv": "Thêm hóa đơn",
        "btnAddStk": "Thêm tồn kho",
        "btnAddMenu": "Thêm thực đơn",
        "btnAddShop": "Thêm sản phẩm cửa hàng",
        "btnAddTx": "Thêm giao dịch",
        "btnAddUsr": "Thêm người dùng",
        "rTitle": "Phòng",
        "rNum": "Số phòng",
        "rType": "Loại phòng",
        "rSgl": "Đơn",
        "rDbl": "Đôi",
        "rSte": "Suite",
        "rBtn": "Thêm phòng",
        "bTitle": "Đặt phòng",
        "bGst": "Khách",
        "bRm": "Phòng",
        "bDate": "Ngày",
        "bBtn": "Thêm đặt phòng",
        "gTitle": "Khách",
        "gName": "Tên",
        "gPhone": "Điện thoại",
        "gId": "ID",
        "gBtn": "Thêm khách",
        "cTitle": "Dọn phòng",
        "cRm": "Phòng",
        "cStat": "Trạng thái",
        "cCln": "Sạch",
        "cDrt": "Bẩn",
        "cPrg": "Đang thực hiện",
        "cBtn": "Lưu",
        "tTitle": "Công việc",
        "tIssue": "Vấn đề",
        "tLoc": "Vị trí",
        "tBtn": "Lưu",
        "sTitle": "Dịch vụ",
        "sRm": "Phòng",
        "sDesc": "Mô tả",
        "sBtn": "Lưu",
        "iTitle": "Hóa đơn",
        "iRef": "Tham chiếu",
        "iAmt": "Số tiền",
        "iBtn": "Lưu",
        "stTitle": "Tồn kho",
        "stItem": "Mặt hàng",
        "stQty": "Số lượng",
        "stBtn": "Lưu",
        "mTitle": "Thực đơn",
        "mDish": "Món ăn",
        "mPrc": "Giá",
        "mBtn": "Lưu",
        "shTitle": "Cửa hàng",
        "shProd": "Sản phẩm",
        "shPrc": "Giá",
        "shBtn": "Lưu",
        "xTitle": "Giao dịch",
        "xDesc": "Mô tả",
        "xAmt": "Số tiền",
        "xBtn": "Lưu",
        "uTitle": "Người dùng",
        "uUser": "Tên người dùng",
        "uRole": "Vai trò",
        "uAdm": "Quản trị",
        "uRec": "Lễ tân",
        "uStf": "Nhân viên",
        "uBtn": "Lưu",
    },
    "id": {
        "sysTitle": "Manajemen hotel, restoran, dan minimarket",
        "btnAddRoom": "Tambah kamar",
        "btnAddBk": "Tambah pemesanan baru",
        "btnAddGst": "Tambah tamu",
        "btnAddCln": "Tambah kebersihan",
        "btnAddTask": "Tambah tugas",
        "btnAddSvc": "Tambah layanan",
        "btnAddInv": "Tambah faktur",
        "btnAddStk": "Tambah stok",
        "btnAddMenu": "Tambah menu",
        "btnAddShop": "Tambah item toko",
        "btnAddTx": "Tambah transaksi",
        "btnAddUsr": "Tambah pengguna",
        "rTitle": "Kamar",
        "rNum": "Nomor kamar",
        "rType": "Tipe kamar",
        "rSgl": "Tunggal",
        "rDbl": "Ganda",
        "rSte": "Suite",
        "rBtn": "Tambah kamar",
        "bTitle": "Pemesanan",
        "bGst": "Tamu",
        "bRm": "Kamar",
        "bDate": "Tanggal",
        "bBtn": "Tambah pemesanan",
        "gTitle": "Tamu",
        "gName": "Nama",
        "gPhone": "Telepon",
        "gId": "ID",
        "gBtn": "Tambah tamu",
        "cTitle": "Kebersihan",
        "cRm": "Kamar",
        "cStat": "Status",
        "cCln": "Bersih",
        "cDrt": "Kotor",
        "cPrg": "Sedang berlangsung",
        "cBtn": "Simpan",
        "tTitle": "Tugas",
        "tIssue": "Masalah",
        "tLoc": "Lokasi",
        "tBtn": "Simpan",
        "sTitle": "Layanan",
        "sRm": "Kamar",
        "sDesc": "Deskripsi",
        "sBtn": "Simpan",
        "iTitle": "Faktur",
        "iRef": "Referensi",
        "iAmt": "Jumlah",
        "iBtn": "Simpan",
        "stTitle": "Stok",
        "stItem": "Item",
        "stQty": "Jumlah",
        "stBtn": "Simpan",
        "mTitle": "Menu",
        "mDish": "Hidangan",
        "mPrc": "Harga",
        "mBtn": "Simpan",
        "shTitle": "Toko",
        "shProd": "Produk",
        "shPrc": "Harga",
        "shBtn": "Simpan",
        "xTitle": "Transaksi",
        "xDesc": "Deskripsi",
        "xAmt": "Jumlah",
        "xBtn": "Simpan",
        "uTitle": "Pengguna",
        "uUser": "Nama pengguna",
        "uRole": "Peran",
        "uAdm": "Admin",
        "uRec": "Resepsi",
        "uStf": "Staf",
        "uBtn": "Simpan",
    },
    "tr": {
        "sysTitle": "Otel, restoran ve minimarket yönetimi",
        "btnAddRoom": "Oda ekle",
        "btnAddBk": "Yeni rezervasyon ekle",
        "btnAddGst": "Misafir ekle",
        "btnAddCln": "Temizlik ekle",
        "btnAddTask": "Görev ekle",
        "btnAddSvc": "Hizmet ekle",
        "btnAddInv": "Fatura ekle",
        "btnAddStk": "Stok ekle",
        "btnAddMenu": "Menü ekle",
        "btnAddShop": "Mağaza ürünü ekle",
        "btnAddTx": "İşlem ekle",
        "btnAddUsr": "Kullanıcı ekle",
        "rTitle": "Oda",
        "rNum": "Oda numarası",
        "rType": "Oda tipi",
        "rSgl": "Tek",
        "rDbl": "Çift",
        "rSte": "Süit",
        "rBtn": "Oda ekle",
        "bTitle": "Rezervasyon",
        "bGst": "Misafir",
        "bRm": "Oda",
        "bDate": "Tarih",
        "bBtn": "Rezervasyon ekle",
        "gTitle": "Misafir",
        "gName": "Ad",
        "gPhone": "Telefon",
        "gId": "Kimlik",
        "gBtn": "Misafir ekle",
        "cTitle": "Temizlik",
        "cRm": "Oda",
        "cStat": "Durum",
        "cCln": "Temiz",
        "cDrt": "Kirli",
        "cPrg": "Devam ediyor",
        "cBtn": "Kaydet",
        "tTitle": "Görev",
        "tIssue": "Sorun",
        "tLoc": "Konum",
        "tBtn": "Kaydet",
        "sTitle": "Hizmet",
        "sRm": "Oda",
        "sDesc": "Açıklama",
        "sBtn": "Kaydet",
        "iTitle": "Fatura",
        "iRef": "Referans",
        "iAmt": "Tutar",
        "iBtn": "Kaydet",
        "stTitle": "Stok",
        "stItem": "Ürün",
        "stQty": "Miktar",
        "stBtn": "Kaydet",
        "mTitle": "Menü",
        "mDish": "Yemek",
        "mPrc": "Fiyat",
        "mBtn": "Kaydet",
        "shTitle": "Mağaza",
        "shProd": "Ürün",
        "shPrc": "Fiyat",
        "shBtn": "Kaydet",
        "xTitle": "İşlem",
        "xDesc": "Açıklama",
        "xAmt": "Tutar",
        "xBtn": "Kaydet",
        "uTitle": "Kullanıcı",
        "uUser": "Kullanıcı adı",
        "uRole": "Rol",
        "uAdm": "Yönetici",
        "uRec": "Resepsiyon",
        "uStf": "Personel",
        "uBtn": "Kaydet",
    },
    "ja": {
        "sysTitle": "ホテル・レストラン・ミニマート管理",
        "btnAddRoom": "部屋を追加",
        "btnAddBk": "新規予約を追加",
        "btnAddGst": "ゲストを追加",
        "btnAddCln": "清掃を追加",
        "btnAddTask": "タスクを追加",
        "btnAddSvc": "サービスを追加",
        "btnAddInv": "請求書を追加",
        "btnAddStk": "在庫を追加",
        "btnAddMenu": "メニューを追加",
        "btnAddShop": "店舗商品を追加",
        "btnAddTx": "取引を追加",
        "btnAddUsr": "ユーザーを追加",
        "rTitle": "部屋",
        "rNum": "部屋番号",
        "rType": "部屋タイプ",
        "rSgl": "シングル",
        "rDbl": "ダブル",
        "rSte": "スイート",
        "rBtn": "部屋を追加",
        "bTitle": "予約",
        "bGst": "ゲスト",
        "bRm": "部屋",
        "bDate": "日付",
        "bBtn": "予約を追加",
        "gTitle": "ゲスト",
        "gName": "名前",
        "gPhone": "電話",
        "gId": "ID",
        "gBtn": "ゲストを追加",
        "cTitle": "清掃",
        "cRm": "部屋",
        "cStat": "ステータス",
        "cCln": "清掃済み",
        "cDrt": "未清掃",
        "cPrg": "作業中",
        "cBtn": "保存",
        "tTitle": "タスク",
        "tIssue": "問題",
        "tLoc": "場所",
        "tBtn": "保存",
        "sTitle": "サービス",
        "sRm": "部屋",
        "sDesc": "説明",
        "sBtn": "保存",
        "iTitle": "請求書",
        "iRef": "参照",
        "iAmt": "金額",
        "iBtn": "保存",
        "stTitle": "在庫",
        "stItem": "品目",
        "stQty": "数量",
        "stBtn": "保存",
        "mTitle": "メニュー",
        "mDish": "料理",
        "mPrc": "価格",
        "mBtn": "保存",
        "shTitle": "ショップ",
        "shProd": "商品",
        "shPrc": "価格",
        "shBtn": "保存",
        "xTitle": "取引",
        "xDesc": "説明",
        "xAmt": "金額",
        "xBtn": "保存",
        "uTitle": "ユーザー",
        "uUser": "ユーザー名",
        "uRole": "役割",
        "uAdm": "管理者",
        "uRec": "フロント",
        "uStf": "スタッフ",
        "uBtn": "保存",
    },
    "ko": {
        "sysTitle": "호텔, 레스토랑, 미니마트 관리",
        "btnAddRoom": "객실 추가",
        "btnAddBk": "새 예약 추가",
        "btnAddGst": "손님 추가",
        "btnAddCln": "청소 추가",
        "btnAddTask": "작업 추가",
        "btnAddSvc": "서비스 추가",
        "btnAddInv": "청구서 추가",
        "btnAddStk": "재고 추가",
        "btnAddMenu": "메뉴 추가",
        "btnAddShop": "매장 상품 추가",
        "btnAddTx": "거래 추가",
        "btnAddUsr": "사용자 추가",
        "rTitle": "객실",
        "rNum": "객실 번호",
        "rType": "객실 유형",
        "rSgl": "싱글",
        "rDbl": "더블",
        "rSte": "스위트",
        "rBtn": "객실 추가",
        "bTitle": "예약",
        "bGst": "손님",
        "bRm": "객실",
        "bDate": "날짜",
        "bBtn": "예약 추가",
        "gTitle": "손님",
        "gName": "이름",
        "gPhone": "전화",
        "gId": "ID",
        "gBtn": "손님 추가",
        "cTitle": "청소",
        "cRm": "객실",
        "cStat": "상태",
        "cCln": "깨끗함",
        "cDrt": "더러움",
        "cPrg": "진행 중",
        "cBtn": "저장",
        "tTitle": "작업",
        "tIssue": "문제",
        "tLoc": "위치",
        "tBtn": "저장",
        "sTitle": "서비스",
        "sRm": "객실",
        "sDesc": "설명",
        "sBtn": "저장",
        "iTitle": "청구서",
        "iRef": "참조",
        "iAmt": "금액",
        "iBtn": "저장",
        "stTitle": "재고",
        "stItem": "품목",
        "stQty": "수량",
        "stBtn": "저장",
        "mTitle": "메뉴",
        "mDish": "요리",
        "mPrc": "가격",
        "mBtn": "저장",
        "shTitle": "매장",
        "shProd": "상품",
        "shPrc": "가격",
        "shBtn": "저장",
        "xTitle": "거래",
        "xDesc": "설명",
        "xAmt": "금액",
        "xBtn": "저장",
        "uTitle": "사용자",
        "uUser": "사용자 이름",
        "uRole": "역할",
        "uAdm": "관리자",
        "uRec": "리셉션",
        "uStf": "직원",
        "uBtn": "저장",
    },
    "ru": {
        "sysTitle": "Управление отелем, рестораном и минимаркетом",
        "btnAddRoom": "Добавить номер",
        "btnAddBk": "Добавить новое бронирование",
        "btnAddGst": "Добавить гостя",
        "btnAddCln": "Добавить уборку",
        "btnAddTask": "Добавить задачу",
        "btnAddSvc": "Добавить услугу",
        "btnAddInv": "Добавить счёт",
        "btnAddStk": "Добавить запас",
        "btnAddMenu": "Добавить меню",
        "btnAddShop": "Добавить товар магазина",
        "btnAddTx": "Добавить транзакцию",
        "btnAddUsr": "Добавить пользователя",
        "rTitle": "Номер",
        "rNum": "Номер комнаты",
        "rType": "Тип номера",
        "rSgl": "Одноместный",
        "rDbl": "Двухместный",
        "rSte": "Люкс",
        "rBtn": "Добавить номер",
        "bTitle": "Бронирование",
        "bGst": "Гость",
        "bRm": "Номер",
        "bDate": "Дата",
        "bBtn": "Добавить бронирование",
        "gTitle": "Гость",
        "gName": "Имя",
        "gPhone": "Телефон",
        "gId": "ID",
        "gBtn": "Добавить гостя",
        "cTitle": "Уборка",
        "cRm": "Номер",
        "cStat": "Статус",
        "cCln": "Чистый",
        "cDrt": "Грязный",
        "cPrg": "В процессе",
        "cBtn": "Сохранить",
        "tTitle": "Задача",
        "tIssue": "Проблема",
        "tLoc": "Местоположение",
        "tBtn": "Сохранить",
        "sTitle": "Услуга",
        "sRm": "Номер",
        "sDesc": "Описание",
        "sBtn": "Сохранить",
        "iTitle": "Счёт",
        "iRef": "Ссылка",
        "iAmt": "Сумма",
        "iBtn": "Сохранить",
        "stTitle": "Запас",
        "stItem": "Товар",
        "stQty": "Количество",
        "stBtn": "Сохранить",
        "mTitle": "Меню",
        "mDish": "Блюдо",
        "mPrc": "Цена",
        "mBtn": "Сохранить",
        "shTitle": "Магазин",
        "shProd": "Продукт",
        "shPrc": "Цена",
        "shBtn": "Сохранить",
        "xTitle": "Транзакция",
        "xDesc": "Описание",
        "xAmt": "Сумма",
        "xBtn": "Сохранить",
        "uTitle": "Пользователь",
        "uUser": "Имя пользователя",
        "uRole": "Роль",
        "uAdm": "Админ",
        "uRec": "Ресепшен",
        "uStf": "Персонал",
        "uBtn": "Сохранить",
    },
    "pt-BR": {
        "sysTitle": "Gestão de hotel, restaurante e minimercado",
        "btnAddRoom": "Adicionar quarto",
        "btnAddBk": "Adicionar nova reserva",
        "btnAddGst": "Adicionar hóspede",
        "btnAddCln": "Adicionar limpeza",
        "btnAddTask": "Adicionar tarefa",
        "btnAddSvc": "Adicionar serviço",
        "btnAddInv": "Adicionar fatura",
        "btnAddStk": "Adicionar estoque",
        "btnAddMenu": "Adicionar cardápio",
        "btnAddShop": "Adicionar item da loja",
        "btnAddTx": "Adicionar transação",
        "btnAddUsr": "Adicionar usuário",
        "rTitle": "Quarto",
        "rNum": "Número do quarto",
        "rType": "Tipo de quarto",
        "rSgl": "Solteiro",
        "rDbl": "Duplo",
        "rSte": "Suíte",
        "rBtn": "Adicionar quarto",
        "bTitle": "Reserva",
        "bGst": "Hóspede",
        "bRm": "Quarto",
        "bDate": "Data",
        "bBtn": "Adicionar reserva",
        "gTitle": "Hóspede",
        "gName": "Nome",
        "gPhone": "Telefone",
        "gId": "ID",
        "gBtn": "Adicionar hóspede",
        "cTitle": "Limpeza",
        "cRm": "Quarto",
        "cStat": "Status",
        "cCln": "Limpo",
        "cDrt": "Sujo",
        "cPrg": "Em andamento",
        "cBtn": "Salvar",
        "tTitle": "Tarefa",
        "tIssue": "Problema",
        "tLoc": "Local",
        "tBtn": "Salvar",
        "sTitle": "Serviço",
        "sRm": "Quarto",
        "sDesc": "Descrição",
        "sBtn": "Salvar",
        "iTitle": "Fatura",
        "iRef": "Referência",
        "iAmt": "Valor",
        "iBtn": "Salvar",
        "stTitle": "Estoque",
        "stItem": "Item",
        "stQty": "Quantidade",
        "stBtn": "Salvar",
        "mTitle": "Cardápio",
        "mDish": "Prato",
        "mPrc": "Preço",
        "mBtn": "Salvar",
        "shTitle": "Loja",
        "shProd": "Produto",
        "shPrc": "Preço",
        "shBtn": "Salvar",
        "xTitle": "Transação",
        "xDesc": "Descrição",
        "xAmt": "Valor",
        "xBtn": "Salvar",
        "uTitle": "Usuário",
        "uUser": "Nome de usuário",
        "uRole": "Função",
        "uAdm": "Admin",
        "uRec": "Recepção",
        "uStf": "Equipe",
        "uBtn": "Salvar",
    },
    "zh-Hans": {
        "sysTitle": "酒店、餐厅及便利店管理",
        "btnAddRoom": "添加房间",
        "btnAddBk": "添加新预订",
        "btnAddGst": "添加客人",
        "btnAddCln": "添加清洁",
        "btnAddTask": "添加任务",
        "btnAddSvc": "添加服务",
        "btnAddInv": "添加发票",
        "btnAddStk": "添加库存",
        "btnAddMenu": "添加菜单",
        "btnAddShop": "添加商店商品",
        "btnAddTx": "添加交易",
        "btnAddUsr": "添加用户",
        "rTitle": "房间",
        "rNum": "房间号",
        "rType": "房间类型",
        "rSgl": "单人",
        "rDbl": "双人",
        "rSte": "套房",
        "rBtn": "添加房间",
        "bTitle": "预订",
        "bGst": "客人",
        "bRm": "房间",
        "bDate": "日期",
        "bBtn": "添加预订",
        "gTitle": "客人",
        "gName": "姓名",
        "gPhone": "电话",
        "gId": "ID",
        "gBtn": "添加客人",
        "cTitle": "清洁",
        "cRm": "房间",
        "cStat": "状态",
        "cCln": "干净",
        "cDrt": "脏",
        "cPrg": "进行中",
        "cBtn": "保存",
        "tTitle": "任务",
        "tIssue": "问题",
        "tLoc": "位置",
        "tBtn": "保存",
        "sTitle": "服务",
        "sRm": "房间",
        "sDesc": "描述",
        "sBtn": "保存",
        "iTitle": "发票",
        "iRef": "参考",
        "iAmt": "金额",
        "iBtn": "保存",
        "stTitle": "库存",
        "stItem": "项目",
        "stQty": "数量",
        "stBtn": "保存",
        "mTitle": "菜单",
        "mDish": "菜品",
        "mPrc": "价格",
        "mBtn": "保存",
        "shTitle": "商店",
        "shProd": "产品",
        "shPrc": "价格",
        "shBtn": "保存",
        "xTitle": "交易",
        "xDesc": "描述",
        "xAmt": "金额",
        "xBtn": "保存",
        "uTitle": "用户",
        "uUser": "用户名",
        "uRole": "角色",
        "uAdm": "管理员",
        "uRec": "前台",
        "uStf": "员工",
        "uBtn": "保存",
    },
    "nl": EMBEDDED_NL,
}


def _lookup_locale(locale_data: dict, section: str, key: str) -> str | None:
    block = locale_data.get(section)
    if isinstance(block, dict):
        val = block.get(key)
        if isinstance(val, str) and val.strip():
            return val
    return None


def build_from_locale_file(code: str) -> dict[str, str]:
    path = LOCALES_DIR / f"{code}.json"
    if not path.is_file():
        return dict(EN)
    locale_data = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, str] = {}
    for pms_key, en_val in EN.items():
        mapped = SOURCE_MAP.get(pms_key)
        if mapped:
            section, loc_key = mapped
            val = _lookup_locale(locale_data, section, loc_key)
            if val:
                out[pms_key] = val
                continue
        out[pms_key] = en_val
    return out


def translate_locale(code: str, target: str, translator_cls) -> dict[str, str]:
    out: dict[str, str] = {}
    for key, en_val in EN.items():
        for attempt in range(4):
            try:
                result = translator_cls(source="en", target=target).translate(en_val)
                if result:
                    out[key] = result
                    break
            except Exception:
                time.sleep(1.0 * (attempt + 1))
        else:
            out[key] = en_val
        time.sleep(0.15)
    return out


def main() -> int:
    if len(EN) != 72:
        print(f"EN must have 72 keys, got {len(EN)}", file=sys.stderr)
        return 1

    payload: dict[str, dict[str, str]] = {"en": dict(EN)}

    for code in EMBEDDED_LOCALES:
        block = EMBEDDED.get(code) or build_from_locale_file(code)
        if len(block) != 72:
            print(f"{code}: expected 72 keys, got {len(block)}", file=sys.stderr)
            return 1
        payload[code] = block

    for code, target in TRANSLATE_TARGETS.items():
        try:
            from deep_translator import GoogleTranslator
        except ImportError:
            print("Install deep-translator: pip install deep-translator", file=sys.stderr)
            return 1
        print(f"Translating {code} via GoogleTranslator ({target})…")
        payload[code] = translate_locale(code, target, GoogleTranslator)

    missing = [loc for loc in APP_LOCALES if loc not in payload]
    if missing:
        print(f"Missing locales: {missing}", file=sys.stderr)
        return 1

    for loc, block in payload.items():
        if len(block) != 72:
            print(f"{loc}: expected 72 keys, got {len(block)}", file=sys.stderr)
            return 1
        extra = set(block) - set(EN)
        if extra:
            print(f"{loc}: unexpected keys {extra}", file=sys.stderr)
            return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    ordered = {loc: payload[loc] for loc in sorted(payload.keys())}
    OUT.write_text(json.dumps(ordered, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(ordered)} locales × {len(EN)} keys)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
